# Generated by Django 5.1.2 on 2024-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="previous_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
